# Generated by Django 5.1.4 on 2025-09-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchQuery',
        ),
    ]
