# Generated by Django 5.1.4 on 2025-09-29 22:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_broadcastrecipient_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='from_chat_id',
            field=models.BigIntegerField(help_text="Xabar kelgan chat ID'si"),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='message_id',
            field=models.BigIntegerField(help_text="Forward qilingan xabar ID'si"),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='scheduled_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Yuborish vaqti'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', help_text='Yuborish holati', max_length=20),
        ),
        migrations.AlterField(
            model_name='broadcastrecipient',
            name='broadcast',
            field=models.ForeignKey(help_text='Mass xabar', on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='bot.broadcast'),
        ),
        migrations.AlterField(
            model_name='broadcastrecipient',
            name='error_message',
            field=models.TextField(blank=True, help_text="Xatolik xabari (agar bo'lsa)", null=True),
        ),
        migrations.AlterField(
            model_name='broadcastrecipient',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Xabar yuborilgan vaqt', null=True),
        ),
        migrations.AlterField(
            model_name='broadcastrecipient',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Yuborish holati', max_length=10),
        ),
        migrations.AlterField(
            model_name='broadcastrecipient',
            name='user',
            field=models.ForeignKey(help_text='Xabar oluvchi foydalanuvchi', on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_messages', to='bot.user'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Joylashuv yuborilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(help_text='GPS kenglik koordinatasi'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(help_text='GPS uzunlik koordinatasi'),
        ),
        migrations.AlterField(
            model_name='location',
            name='user',
            field=models.ForeignKey(help_text='Joylashuv yuborgan foydalanuvchi', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='bot.user'),
        ),
        migrations.AlterField(
            model_name='subscribechannel',
            name='active',
            field=models.BooleanField(default=True, help_text="Kanal faol yoki yo'q"),
        ),
        migrations.AlterField(
            model_name='subscribechannel',
            name='channel_id',
            field=models.CharField(help_text="Telegram kanal ID'si", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subscribechannel',
            name='channel_link',
            field=models.URLField(blank=True, help_text='Kanal havolasi (shaxsiy kanallar uchun)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscribechannel',
            name='channel_username',
            field=models.CharField(blank=True, help_text="Telegram kanal username'i (@channel_name)", max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscribechannel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='subscribechannel',
            name='private',
            field=models.BooleanField(default=False, help_text="Shaxsiy kanal yoki yo'q"),
        ),
        migrations.AlterField(
            model_name='subscribechannel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text="Ro'yxatdan o'tgan vaqt"),
        ),
        migrations.AlterField(
            model_name='user',
            name='deeplink',
            field=models.TextField(blank=True, help_text="Chuqur havola ma'lumoti", null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='Foydalanuvchi ismi', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Admin huquqlari'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Bloklangan holat'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Oxirgi faollik vaqti'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='Foydalanuvchi familiyasi', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='left',
            field=models.BooleanField(default=False, help_text="Botni tark etgan yoki yo'q"),
        ),
        migrations.AlterField(
            model_name='user',
            name='search_mode',
            field=models.CharField(choices=[('normal', 'Normal'), ('deep', 'Deep')], db_index=True, default='normal', help_text='Qidiruv rejimi', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='selected_language',
            field=models.CharField(blank=True, choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], help_text='Tanlangan til', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='stock_language',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='uz', help_text='Asosiy til', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Oxirgi yangilanish vaqti'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text="Telegram username'i", max_length=100, null=True),
        ),
    ]
