# Generated by Django 5.1.4 on 2025-11-10 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_broadcast_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, help_text='Telegram user ID', unique=True)),
                ('first_name', models.CharField(blank=True, help_text='Foydalanuvchi ismi', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Foydalanuvchi familiyasi', max_length=100, null=True)),
                ('username', models.CharField(blank=True, help_text="Telegram username'i", max_length=100, null=True)),
                ('last_active', models.DateTimeField(auto_now=True, db_index=True, help_text='Oxirgi faollik vaqti')),
                ('is_admin', models.BooleanField(default=False, help_text='Admin huquqlari')),
                ('is_blocked', models.BooleanField(default=False, help_text='Bloklangan holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Ro'yxatdan o'tgan vaqt")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Oxirgi yangilanish vaqti')),
                ('stock_language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='uz', help_text='Asosiy til', max_length=10)),
                ('selected_language', models.CharField(blank=True, choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], help_text='Tanlangan til', max_length=10, null=True)),
                ('deeplink', models.TextField(blank=True, help_text="Chuqur havola ma'lumoti", null=True)),
                ('left', models.BooleanField(default=False, help_text="Botni tark etgan yoki yo'q")),
                ('search_mode', models.CharField(choices=[('normal', 'Normal'), ('deep', 'Deep')], db_index=True, default='normal', help_text='Qidiruv rejimi', max_length=10)),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
            },
        ),
        migrations.AlterField(
            model_name='broadcastrecipient',
            name='user',
            field=models.ForeignKey(help_text='Xabar oluvchi foydalanuvchi', on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_messages', to='bot.telegramuser'),
        ),
        migrations.AlterField(
            model_name='location',
            name='user',
            field=models.ForeignKey(help_text='Joylashuv yuborgan foydalanuvchi', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='bot.telegramuser'),
        ),
    ]
