# Generated by Django 5.1.4 on 2025-11-10 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_rename_user_to_telegramuser'),
        ('files', '0021_rename_user_to_telegramuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
