# Generated by Django 5.2.6 on 2025-09-18 13:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parse_file_url', models.TextField(blank=True, help_text='Direct link to the document file', null=True, verbose_name='File URL')),
                ('file_path', models.TextField(blank=True, help_text='Path where file is saved locally', null=True, verbose_name='Local File Path')),
                ('is_indexed', models.BooleanField(db_index=True, default=False, verbose_name='Is Indexed in Elasticsearch')),
                ('is_download_status', models.BooleanField(db_index=True, default=False, verbose_name='Download Status')),
                ('is_deleted_status', models.BooleanField(db_index=True, default=False, verbose_name='Delete_from_Server')),
                ('is_telegram_status', models.BooleanField(db_index=True, default=False, verbose_name='Telegram Status')),
                ('telegram_file_id', models.TextField(blank=True, db_index=True, help_text='File ID after sending to Telegram channel', null=True, verbose_name='Telegram File ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('json_data', models.JSONField(blank=True, null=True, verbose_name='JSON Data')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParseProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_page', models.IntegerField(default=0, verbose_name='Last Parsed Page')),
                ('total_pages_parsed', models.IntegerField(default=0, verbose_name='Total Pages Parsed')),
                ('last_run_at', models.DateTimeField(auto_now=True, verbose_name='Last Run At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Parse Progress',
                'verbose_name_plural': 'Parse Progress',
                'ordering': ['-last_run_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(choices=[('soff', 'soff'), ('arxiv', 'arxiv')], unique=True)),
                ('token', models.TextField(unique=True)),
                ('auth_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Product ID')),
                ('title', models.TextField(db_index=True, verbose_name='Title')),
                ('parsed_content', models.TextField(blank=True, null=True, verbose_name='Parsed Content')),
                ('slug', models.TextField(db_index=True, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='files.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
