# Generated by Django 5.2.6 on 2025-09-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_sitetoken_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetoken',
            name='token',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
