# Generated by Django 5.1.4 on 2025-09-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_sitetoken_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_deleted_status',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_download_status',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_indexed',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_telegram_status',
        ),
        migrations.AddField(
            model_name='document',
            name='delete_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Tugatildi'), ('failed', 'Xatolik'), ('skipped', 'O`tkazib yuborildi')], default='pending', max_length=20, verbose_name="O'chirish holati"),
        ),
        migrations.AddField(
            model_name='document',
            name='download_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Tugatildi'), ('failed', 'Xatolik'), ('skipped', 'O`tkazib yuborildi')], default='pending', max_length=20, verbose_name='Yuklab olish holati'),
        ),
        migrations.AddField(
            model_name='document',
            name='index_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Tugatildi'), ('failed', 'Xatolik'), ('skipped', 'O`tkazib yuborildi')], default='pending', max_length=20, verbose_name='Indekslash holati'),
        ),
        migrations.AddField(
            model_name='document',
            name='parse_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Tugatildi'), ('failed', 'Xatolik'), ('skipped', 'O`tkazib yuborildi')], default='pending', max_length=20, verbose_name='Parse qilish holati'),
        ),
        migrations.AddField(
            model_name='document',
            name='telegram_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Tugatildi'), ('failed', 'Xatolik'), ('skipped', 'O`tkazib yuborildi')], default='pending', max_length=20, verbose_name='Telegram holati'),
        ),
    ]
