# Generated by Django 5.1.4 on 2025-09-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_remove_document_is_deleted_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='telegram_file_id',
            field=models.CharField(blank=True, db_index=True, help_text='File ID after sending to Telegram channel', max_length=500, null=True, verbose_name='Telegram File ID'),
        ),
    ]
