# Generated by Django 5.1.4 on 2025-09-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_document_telegram_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Barchasi tugatildimi?'),
        ),
    ]
