# Generated by Django 5.1.4 on 2025-09-19 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_searchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pipeline_running',
            field=models.BooleanField(db_index=True, default=False, help_text='Pipeline hozir ushbu hujjat ustida ishlayotganini bildiradi'),
        ),
        migrations.AlterField(
            model_name='document',
            name='completed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Barchasi tugatildimi?'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
