# Generated by Django 5.1.4 on 2025-09-23 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_remove_document_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('download', 'Yuklab olish xatoligi'), ('telegram_send', 'Telegramga yuborish xatoligi'), ('telegram_download', 'Telegramdan yuklab olish xatoligi'), ('parse', 'Parse qilish xatoligi'), ('index', 'Indekslash xatoligi'), ('other', 'Boshqa xatolik')], max_length=20, verbose_name='Xatolik turi')),
                ('error_message', models.TextField(verbose_name='Xatolik xabari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='files.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Document Error',
                'verbose_name_plural': 'Document Errors',
                'ordering': ['-created_at'],
            },
        ),
    ]
