# Generated by Django 5.1.4 on 2025-09-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_documenterror_celery_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='download_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Download Count'),
        ),
        migrations.AddField(
            model_name='product',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='File Size (bytes)'),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='View Count'),
        ),
    ]
