# Generated by Django 5.1.4 on 2025-09-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_documentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='delete_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Tugatildi'), ('failed', 'Xatolik'), ('skipped', 'O`tkazib yuborildi')], db_index=True, default='pending', max_length=20, verbose_name="O'chirish holati"),
        ),
        migrations.AlterField(
            model_name='document',
            name='download_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Tugatildi'), ('failed', 'Xatolik'), ('skipped', 'O`tkazib yuborildi')], db_index=True, default='pending', max_length=20, verbose_name='Yuklab olish holati'),
        ),
        migrations.AlterField(
            model_name='document',
            name='index_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Tugatildi'), ('failed', 'Xatolik'), ('skipped', 'O`tkazib yuborildi')], db_index=True, default='pending', max_length=20, verbose_name='Indekslash holati'),
        ),
        migrations.AlterField(
            model_name='document',
            name='parse_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Tugatildi'), ('failed', 'Xatolik'), ('skipped', 'O`tkazib yuborildi')], db_index=True, default='pending', max_length=20, verbose_name='Parse qilish holati'),
        ),
        migrations.AlterField(
            model_name='document',
            name='telegram_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Tugatildi'), ('failed', 'Xatolik'), ('skipped', 'O`tkazib yuborildi')], db_index=True, default='pending', max_length=20, verbose_name='Telegram holati'),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='documenterror',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='documenterror',
            name='error_type',
            field=models.CharField(choices=[('download', 'Yuklab olish xatoligi'), ('telegram_send', 'Telegramga yuborish xatoligi'), ('telegram_download', 'Telegramdan yuklab olish xatoligi'), ('parse', 'Parse qilish xatoligi'), ('index', 'Indekslash xatoligi'), ('other', 'Boshqa xatolik')], db_index=True, max_length=20, verbose_name='Xatolik turi'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='found_results',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='is_deep_search',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='query_text',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
