# Generated by Django 5.1.4 on 2025-10-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_alter_document_completed_alter_document_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(help_text='Mahsulotning noyob identifikatori', primary_key=True, serialize=False, verbose_name='Product ID'),
        ),
    ]
