# Generated by Django 5.1.4 on 2025-10-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0017_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.TextField(blank=True, db_index=True, help_text="URL uchun slug (masalan: 'matematika-darsligi')", null=True, unique=True, verbose_name='Slug'),
        ),
    ]
