# Generated by Django 5.1.4 on 2025-10-06 22:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0018_alter_product_slug_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Hujjatning noyub identifikatori', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(help_text='Mahsulotning noyub identifikatori', primary_key=True, serialize=False, verbose_name='Product ID'),
        ),
    ]
