# Generated by Django 5.1.4 on 2025-11-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0021_rename_user_to_telegramuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParseProgress',
        ),
    ]
