# Generated by Django 5.1.4 on 2025-11-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0022_delete_parseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Fayl hajmi (baytda)'),
        ),
        migrations.AddField(
            model_name='document',
            name='page_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sahifalar soni'),
        ),
    ]
