# Generated by Django 5.1.4 on 2025-11-17 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0023_document_file_size_document_page_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentimage',
            options={'ordering': ['page_number'], 'verbose_name': 'Hujjat Rasmi', 'verbose_name_plural': 'Hujjat Rasmlari'},
        ),
        migrations.RemoveField(
            model_name='documentimage',
            name='image',
        ),
        migrations.AddField(
            model_name='documentimage',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to='document_images/large/', verbose_name='Katta rasm (WebP)'),
        ),
        migrations.AddField(
            model_name='documentimage',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='document_images/small/', verbose_name='Kichik rasm (WebP)'),
        ),
        migrations.AlterField(
            model_name='documentimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documentimage',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='files.document'),
        ),
        migrations.AlterField(
            model_name='documentimage',
            name='page_number',
            field=models.IntegerField(default=1, verbose_name='Sahifa raqami'),
        ),
    ]
