"""
Django Settings for FileFinder Project
======================================

Bu fayl Django loyihasining asosiy sozlamalarini o'z ichiga oladi.
FileFinder - Telegram bot orqali hujjatlar qidirish va yuklab olish platformasi.

Asosiy xususiyatlar:
- Telegram bot integratsiyasi
- Elasticsearch qidiruv tizimi
- Celery background tasks
- Admin panel optimizatsiyasi
- File parsing va indexing
- Multi-language support

Sozlamalar:
- DEBUG: Development/Production rejimi
- SECRET_KEY: Django xavfsizlik kaliti
- ALLOWED_HOSTS: Ruxsat berilgan hostlar
- INSTALLED_APPS: O'rnatilgan Django applar
- DATABASES: Ma'lumotlar bazasi sozlamalari
- CACHES: Cache tizimi sozlamalari
- CELERY: Background tasks sozlamalari
- ELASTICSEARCH: Qidiruv tizimi sozlamalari

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv
from .jazzmin_conf import JAZZMIN_SETTINGS, JAZZMIN_UI_TWEAKS

# Import admin optimizations
try:
    from .admin_optimizations import optimize_admin_performance
    optimize_admin_performance()
except ImportError:
    pass

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# SECURITY SETTINGS - Xavfsizlik sozlamalari
# =============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
# Django loyihasi uchun maxsus xavfsizlik kaliti
# Production'da mutlaqo maxfiy saqlanishi kerak
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-2l_(+n_3abqx8re_4sn263o*9@vhm_mg_3g!_2m(6ssynqgbtv')

# SECURITY WARNING: don't run with debug turned on in production!
# Debug rejimi - development'da True, production'da False bo'lishi kerak
# Debug=True bo'lganda batafsil xatolik ma'lumotlari ko'rsatiladi
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

# Ruxsat berilgan hostlar - server nomlari
# Production'da faqat haqiqiy domain nomlari qo'shilishi kerak
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver,fayltop.cloud').split(',') if os.getenv('ALLOWED_HOSTS') else ['localhost', '127.0.0.1', 'testserver', 'fayltop.cloud']


# =============================================================================
# APPLICATION DEFINITION - Django applar ro'yxati
# =============================================================================

INSTALLED_APPS = [
    # Django admin panel uchun Jazzmin theme
    'jazzmin',
    
    # Django built-in applar
    'django.contrib.admin',        # Admin panel
    'django.contrib.auth',         # Autentifikatsiya tizimi
    'django.contrib.contenttypes', # Content types framework
    'django.contrib.sessions',     # Session management
    'django.contrib.messages',     # Message framework
    'django.contrib.staticfiles',  # Static files handling
    
    # Loyiha applar
    'apps.files',      # Fayllar bilan ishlash (parsing, indexing)
    'apps.bot',        # Telegram bot funksionalligi
    'apps.core_api',   # API endpoints
    
    # Third-party applar
    'corsheaders',           # CORS (Cross-Origin Resource Sharing)
    'drf_yasg',             # Swagger API documentation
    'rest_framework',        # Django REST Framework
    'rest_framework.authtoken', # Token authentication
    'django_celery_results', # Celery task results
    'django_celery_beat',    # Celery periodic tasks
]

MIDDLEWARE = [
    # Xavfsizlik middleware - HTTPS, XSS protection
    'django.middleware.security.SecurityMiddleware',
    
    # Static files serving middleware
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
    # CORS middleware - Cross-Origin Resource Sharing
    'corsheaders.middleware.CorsMiddleware',
    
    # Session middleware - user sessions
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    # Common middleware - URL rewriting, etc.
    'django.middleware.common.CommonMiddleware',
    
    # CSRF protection middleware
    'django.middleware.csrf.CsrfViewMiddleware',
    
    # Authentication middleware
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    
    # Message middleware - flash messages
    'django.contrib.messages.middleware.MessageMiddleware',
    
    # Clickjacking protection
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Upload directory settings
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use SQLite for development/testing
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'filefinder_db'),
        'USER': os.getenv('POSTGRES_USER', 'sherzamon'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'filefinder_pass'),
        'HOST': os.getenv('POSTGRES_HOST', 'postgres'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
        'CONN_MAX_AGE': 600,  # Connection pooling uchun
        'OPTIONS': {
            'connect_timeout': 10,
        },
    }
}




ADMIN_OPTIMIZATIONS = {
    'ENABLE_CACHE': True,
    'CACHE_TIMEOUT': 300,  # 5 daqiqa
    'PAGINATION_SIZE': 25,
    'ENABLE_SELECT_RELATED': True,
    'ENABLE_PREFETCH_RELATED': True,
    'ENABLE_QUERYSET_OPTIMIZATION': True,
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Temporary files directory
TEMP_DIR = os.path.join(BASE_DIR, 'temp')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files configuration for production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://fayltop.cloud",
    "http://localhost:18000",
    "http://127.0.0.1:18000",
]
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.fayltop\.cloud$",
]

# Redis Cache Configuration for Admin Panel Optimization
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 900,  # 15 daqiqa (900 seconds) - optimized for search
        'OPTIONS': {
            'MAX_ENTRIES': 5000,  # Increased cache size
            'CULL_FREQUENCY': 2,  # More aggressive caching
        }
    }
}

# Redis Cache Configuration (Production uchun)
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': 'redis://redis:6379/0',
#         'TIMEOUT': 180,  # 3 daqiqa (180 seconds)
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#             'CONNECTION_POOL_KWARGS': {
#                 'max_connections': 50,
#                 'retry_on_timeout': True,
#             },
#             'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
#             'SERIALIZER': 'django_redis.serializers.json.JSONSerializer',
#         }
#     }
# }

# Admin Panel Performance Optimizations
ADMIN_OPTIMIZATIONS = {
    'ENABLE_CACHE': True,
    'CACHE_TIMEOUT': 180,  # 3 daqiqa (180 seconds)
    'PAGINATION_SIZE': 25,
    'ENABLE_SELECT_RELATED': True,
    'ENABLE_PREFETCH_RELATED': True,
    'ENABLE_QUERYSET_OPTIMIZATION': True,
}

# CSRF Configuration
CSRF_TRUSTED_ORIGINS = [
    "https://fayltop.cloud",
    "http://localhost:18000",
    "http://127.0.0.1:18000",
]
CSRF_COOKIE_SECURE = False  # Development uchun False, production da True bo'lishi kerak
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'

# =============================================================================
# DJANGO REST FRAMEWORK CONFIGURATION - API sozlamalari
# =============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# =============================================================================
# CELERY CONFIGURATION - Background tasks sozlamalari
# =============================================================================

# Celery broker URL - Development uchun database
BROKER_URL = os.getenv('CELERY_BROKER_URL', 'django-db')

# Celery result backend - Django database
RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'django-db')

# Test uchun Celery sozlamalari
if 'test' in sys.argv:
    # Test muhitida Celery'ni disable qilish
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
    CELERY_BROKER_URL = 'memory://'
    CELERY_RESULT_BACKEND = 'cache+memory://'

# Celery task serialization
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# Celery timezone
CELERY_TIMEZONE = 'Asia/Tashkent'
CELERY_ENABLE_UTC = True

# Celery task tracking
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 daqiqa
CELERY_TASK_SOFT_TIME_LIMIT = 60  # 1 daqiqa

# Celery result backend settings
CELERY_RESULT_BACKEND_DB = 'django-db'
CELERY_RESULT_EXPIRES = 3600  # 1 soat

# Celery beat scheduler
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Main URL configuration - Auto-detect environment
if DEBUG:
    MAIN_URL = os.getenv('MAIN_URL', 'http://127.0.0.1:8000')
else:
    MAIN_URL = os.getenv('MAIN_URL', 'https://fayltop.cloud')

# External Services Configuration
ES_URL = os.getenv('ES_URL', 'http://localhost:9200')
ES_INDEX = os.getenv('ES_INDEX', 'documents')
TIKA_URL = os.getenv('TIKA_URL', 'http://tika:9998')

# Telegram Bot Configuration
BOT_TOKEN = os.getenv('BOT_TOKEN', '')
BOT_USERNAME = os.getenv('BOT_USERNAME', 'fayltopbot')
CHANNEL_ID = os.getenv('CHANNEL_ID', '')
WEBHOOK_URL = os.getenv('WEBHOOK_URL', '')

# =============================================================================
# LOGGING CONFIGURATION - Proper logging framework
# =============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'json': {
            'format': '{"level": "%(levelname)s", "time": "%(asctime)s", "module": "%(module)s", "message": "%(message)s"}',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'maxBytes': 1024*1024*15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'error.log'),
            'maxBytes': 1024*1024*15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'celery_file': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'celery': {
            'handlers': ['celery_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery.task': {
            'handlers': ['celery_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.files': {
            'handlers': ['file', 'console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.bot': {
            'handlers': ['file', 'console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.core_api': {
            'handlers': ['file', 'console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.files.tasks': {
            'handlers': ['file', 'console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.files.tasks.document_processing': {
            'handlers': ['file', 'console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)