# Generated by Django 5.1.4 on 2025-09-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_delete_searchquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastrecipient',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='search_mode',
            field=models.CharField(choices=[('normal', 'Normal'), ('deep', 'Deep')], db_index=True, default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(db_index=True, help_text='Telegram user ID', unique=True),
        ),
    ]
