# Generated by Django 5.0.8 on 2025-09-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_document_pipeline_running_alter_document_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
    ]
