# Generated by Django 5.1.4 on 2025-09-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_documenterror'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenterror',
            name='celery_attempt',
            field=models.PositiveIntegerField(default=1, help_text='Bu xatolik qaysi urinishda yuz bergani', verbose_name='Celery urinish raqami'),
        ),
    ]
