# Generated by Django 5.1.4 on 2025-09-29 22:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_broadcast_created_at_and_more'),
        ('files', '0015_alter_documentimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='completed',
            field=models.BooleanField(db_index=True, default=False, help_text="Hujjat barcha jarayonlardan o'tganmi", verbose_name='Barchasi tugatildimi?'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Hujjat yaratilgan vaqt', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='document',
            name='delete_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Tugatildi'), ('failed', 'Xatolik'), ('skipped', 'O`tkazib yuborildi')], db_index=True, default='pending', help_text="Hujjat o'chirish jarayoni holati", max_length=20, verbose_name="O'chirish holati"),
        ),
        migrations.AlterField(
            model_name='document',
            name='download_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Tugatildi'), ('failed', 'Xatolik'), ('skipped', 'O`tkazib yuborildi')], db_index=True, default='pending', help_text='Hujjat yuklab olish jarayoni holati', max_length=20, verbose_name='Yuklab olish holati'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Hujjatning noyob identifikatori', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='index_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Tugatildi'), ('failed', 'Xatolik'), ('skipped', 'O`tkazib yuborildi')], db_index=True, default='pending', help_text='Hujjat indekslash jarayoni holati', max_length=20, verbose_name='Indekslash holati'),
        ),
        migrations.AlterField(
            model_name='document',
            name='json_data',
            field=models.JSONField(blank=True, help_text="Hujjat bilan bog'liq qo'shimcha JSON ma'lumotlar", null=True, verbose_name='JSON Data'),
        ),
        migrations.AlterField(
            model_name='document',
            name='parse_file_url',
            field=models.TextField(blank=True, help_text="Hujjat faylining to'g'ridan-to'g'ri havolasi", null=True, verbose_name='File URL'),
        ),
        migrations.AlterField(
            model_name='document',
            name='parse_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Tugatildi'), ('failed', 'Xatolik'), ('skipped', 'O`tkazib yuborildi')], db_index=True, default='pending', help_text='Hujjat parse qilish jarayoni holati', max_length=20, verbose_name='Parse qilish holati'),
        ),
        migrations.AlterField(
            model_name='document',
            name='telegram_file_id',
            field=models.CharField(blank=True, db_index=True, help_text="Telegram kanaliga yuborilgandan keyin fayl ID'si", max_length=500, null=True, verbose_name='Telegram File ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='telegram_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Tugatildi'), ('failed', 'Xatolik'), ('skipped', 'O`tkazib yuborildi')], db_index=True, default='pending', help_text="Telegram'ga yuborish jarayoni holati", max_length=20, verbose_name='Telegram holati'),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Hujjat oxirgi yangilangan vaqt', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='documenterror',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Xatolik yuz bergan vaqt', verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='documenterror',
            name='document',
            field=models.ForeignKey(help_text='Xatolik yuz bergan hujjat', on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='files.document', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='documenterror',
            name='error_message',
            field=models.TextField(help_text='Xatolikning batafsil tavsifi', verbose_name='Xatolik xabari'),
        ),
        migrations.AlterField(
            model_name='documenterror',
            name='error_type',
            field=models.CharField(choices=[('download', 'Yuklab olish xatoligi'), ('telegram_send', 'Telegramga yuborish xatoligi'), ('telegram_download', 'Telegramdan yuklab olish xatoligi'), ('parse', 'Parse qilish xatoligi'), ('index', 'Indekslash xatoligi'), ('other', 'Boshqa xatolik')], db_index=True, help_text='Xatolikning turi', max_length=20, verbose_name='Xatolik turi'),
        ),
        migrations.AlterField(
            model_name='documentimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Rasm yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='documentimage',
            name='document',
            field=models.ForeignKey(help_text="Rasm tegishli bo'lgan hujjat", on_delete=django.db.models.deletion.CASCADE, related_name='images', to='files.document'),
        ),
        migrations.AlterField(
            model_name='documentimage',
            name='image',
            field=models.ImageField(help_text='Hujjat sahifasining rasm fayli', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='documentimage',
            name='page_number',
            field=models.PositiveIntegerField(help_text='Sahifa raqami'),
        ),
        migrations.AlterField(
            model_name='parseprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Parse progress yaratilgan vaqt', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='parseprogress',
            name='id',
            field=models.AutoField(help_text="Parse progress ID'si", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parseprogress',
            name='last_page',
            field=models.IntegerField(default=0, help_text='Oxirgi parse qilingan sahifa raqami', verbose_name='Last Parsed Page'),
        ),
        migrations.AlterField(
            model_name='parseprogress',
            name='last_run_at',
            field=models.DateTimeField(auto_now=True, help_text='Oxirgi parse jarayoni boshlangan vaqt', verbose_name='Last Run At'),
        ),
        migrations.AlterField(
            model_name='parseprogress',
            name='total_pages_parsed',
            field=models.IntegerField(default=0, help_text='Jami parse qilingan sahifalar soni', verbose_name='Total Pages Parsed'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Mahsulot yaratilgan vaqt', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='document',
            field=models.OneToOneField(help_text="Bog'langan hujjat", on_delete=django.db.models.deletion.CASCADE, related_name='product', to='files.document', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='product',
            name='download_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Mahsulotni yuklab olishlar soni', verbose_name='Download Count'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, help_text='Fayl hajmi baytlarda', verbose_name='File Size (bytes)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(help_text='Mahsulotning noyob identifikatori', primary_key=True, serialize=False, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='parsed_content',
            field=models.TextField(blank=True, help_text='Hujjatdan parse qilingan matn kontenti', null=True, verbose_name='Parsed Content'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.TextField(db_index=True, help_text="URL uchun slug (masalan: 'matematika-darsligi')", unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(db_index=True, help_text='Mahsulot sarlavhasi', verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Mahsulot oxirgi yangilangan vaqt', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text="Mahsulotni ko'rishlar soni", verbose_name='View Count'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Qidiruv amalga oshirilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='found_results',
            field=models.BooleanField(db_index=True, default=False, help_text='Qidiruv natijalari topildimi'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='is_deep_search',
            field=models.BooleanField(db_index=True, default=False, help_text='Chuqur qidiruv rejimi ishlatildimi'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='query_text',
            field=models.CharField(db_index=True, help_text="Qidiruv so'rovi matni", max_length=500),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='user',
            field=models.ForeignKey(help_text='Qidiruv qilgan foydalanuvchi', on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to='bot.user'),
        ),
        migrations.AlterField(
            model_name='sitetoken',
            name='auth_token',
            field=models.TextField(blank=True, help_text="Qo'shimcha autentifikatsiya token'i", null=True),
        ),
        migrations.AlterField(
            model_name='sitetoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Token yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='sitetoken',
            name='name',
            field=models.CharField(choices=[('soff', 'soff'), ('arxiv', 'arxiv')], help_text='Sayt nomi (soff yoki arxiv)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sitetoken',
            name='token',
            field=models.CharField(help_text="Asosiy autentifikatsiya token'i", max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='sitetoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Token oxirgi yangilangan vaqt'),
        ),
    ]
