# Generated by Django 5.1.4 on 2025-10-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0019_alter_document_id_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='blocked',
            field=models.BooleanField(db_index=True, default=False, help_text='Mahsulot bloklangan (Access Denied xatolari uchun)', verbose_name='Blocked'),
        ),
        migrations.AddField(
            model_name='product',
            name='blocked_at',
            field=models.DateTimeField(blank=True, help_text='Bloklangan vaqt', null=True, verbose_name='Blocked At'),
        ),
        migrations.AddField(
            model_name='product',
            name='blocked_reason',
            field=models.TextField(blank=True, help_text='Bloklanish sababi', null=True, verbose_name='Blocked Reason'),
        ),
    ]
