# Generated by Django 5.1.4 on 2025-11-10 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_rename_user_to_telegramuser'),
        ('files', '0020_add_blocked_fields_to_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenterror',
            name='error_type',
            field=models.CharField(choices=[('download', 'Yuklab olish xatoligi'), ('telegram_send', 'Telegramga yuborish xatoligi'), ('telegram_download', 'Telegramdan yuklab olish xatoligi'), ('parse', 'Parse qilish xatoligi'), ('tika_timeout', 'Tika server timeout xatoligi'), ('tika_connection', 'Tika server ulanish xatoligi'), ('tika_parse', 'Tika parse xatoligi'), ('index', 'Indekslash xatoligi'), ('other', 'Boshqa xatolik')], db_index=True, help_text='Xatolikning turi', max_length=20, verbose_name='Xatolik turi'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='user',
            field=models.ForeignKey(help_text='Qidiruv qilgan foydalanuvchi', on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to='bot.telegramuser'),
        ),
    ]
