# Generated by Django 5.1.4 on 2025-11-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0024_alter_documentimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(db_index=True, help_text="Qidiruv so'rovi matni", max_length=500)),
                ('found_results', models.BooleanField(db_index=True, default=False, help_text='Qidiruv natijalari topildimi')),
                ('is_deep_search', models.BooleanField(db_index=True, default=False, help_text='Chuqur qidiruv rejimi ishlatildimi')),
                ('result_count', models.IntegerField(db_index=True, default=0, help_text='Topilgan natijalar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Qidiruv amalga oshirilgan vaqt')),
            ],
            options={
                'verbose_name': "Web Qidiruv So'rovi",
                'verbose_name_plural': "Web Qidiruv So'rovlari",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query_text', 'created_at'], name='files_webse_query_t_bcf07f_idx'), models.Index(fields=['is_deep_search', 'found_results'], name='files_webse_is_deep_f85349_idx')],
            },
        ),
    ]
